workflows:
  ios-workflow:
    name: iOS Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.indotech.urjaview"
        APP_NAME: "UrjaView"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: ios-*
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Set up dependencies
        script: |
          flutter pub get
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze || true
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/tmp/export_options.plist || \
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - team@indotechworks.com
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Release
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 11
      vars:
        BUNDLE_ID: "com.indotech.urjaview"
        APP_NAME: "UrjaView"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: android-*
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Set up debug signing
        script: |
          # Use debug signing for now
          echo "Using debug signing configuration"
      - name: Set up dependencies
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze || true
      - name: Flutter build app bundle
        script: |
          BUILD_NUMBER=${BUILD_NUMBER:-1}
          BUILD_NAME=$(echo ${CM_TAG:-1.0.0} | sed 's/android-//')
          flutter build appbundle --release \
            --build-number=$BUILD_NUMBER \
            --build-name=$BUILD_NAME
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - team@indotechworks.com
        notify:
          success: true
          failure: true