workflows:
  ios-workflow:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.indotech.urjaview
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.indotech.urjaview"
        APP_NAME: "UrjaView"
        # Increment build number automatically
        APP_STORE_APPLE_ID: 6749311837
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: ios-*
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Set up local properties
        script: |
          echo "Building version ${CM_TAG:-1.0.0}"
      - name: Set up dependencies
        script: |
          flutter pub get
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze --fatal-warnings
      - name: Set up code signing
        script: |
          # Fetch signing files from App Store Connect
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          
          # Use the fetched profiles
          xcode-project use-profiles
      - name: Flutter build iOS
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=$(echo ${CM_TAG:-1.0.0} | sed 's/ios-//') \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - team@indotechworks.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

  android-workflow:
    name: Android Release
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 11
      vars:
        BUNDLE_ID: "com.indotech.urjaview"
        APP_NAME: "UrjaView"
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: android-*
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Set up debug signing
        script: |
          # Use debug signing for now
          echo "Using debug signing configuration"
      - name: Set up dependencies
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze || true
      - name: Flutter build app bundle
        script: |
          BUILD_NUMBER=${BUILD_NUMBER:-1}
          BUILD_NAME=$(echo ${CM_TAG:-1.0.0} | sed 's/android-//')
          flutter build appbundle --release \
            --build-number=$BUILD_NUMBER \
            --build-name=$BUILD_NAME
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - team@indotechworks.com
        notify:
          success: true
          failure: true