default_platform(:android)

platform :android do
  desc "Deploy app with screenshots to the Google Play Store"
  lane :deployapp do |options|
    supply(
      package_name: "com.indotech.urjaview",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_aab: false,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      json_key: "google-play-store.json",
      track: "internal",
      metadata_path: "./fastlane/metadata/android",
      version_code: options[:versionCode].to_i
    )
  end

  desc "Upload only screenshots to Google Play Store"
  lane :upload_screenshots do
    supply(
      package_name: "com.indotech.urjaview",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      json_key: "google-play-store.json",
      metadata_path: "./fastlane/metadata/android"
    )
  end

  desc "Download metadata and screenshots from Google Play Store"
  lane :download_metadata do
    supply(
      package_name: "com.indotech.urjaview",
      json_key: "google-play-store.json",
      metadata_path: "./fastlane/metadata/android",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      download_metadata: true
    )
  end
end